"""intial_migrations

Revision ID: 5f85416c7218
Revises: 
Create Date: 2026-06-03 08:48:35.141344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f85416c7218'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_ticker'), 'entities', ['ticker'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rss_url', sa.Text(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('archive_day_range', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'FAILED', name='source_status_enum'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_url')
    )
    op.create_index(op.f('ix_sources_is_active'), 'sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment_enum'), nullable=False),
    sa.Column('news_metadata', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('article_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_hash'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_entity_date', 'news', ['entity_id', 'published_date'], unique=False)
    op.create_index('idx_news_sentiment_date', 'news', ['sentiment', 'published_date'], unique=False)
    op.create_index('idx_news_source_date', 'news', ['source_name', 'published_date'], unique=False)
    op.create_index(op.f('ix_news_entity_id'), 'news', ['entity_id'], unique=False)
    op.create_index(op.f('ix_news_published_date'), 'news', ['published_date'], unique=False)
    op.create_index(op.f('ix_news_sentiment'), 'news', ['sentiment'], unique=False)
    op.create_index(op.f('ix_news_source_name'), 'news', ['source_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_source_name'), table_name='news')
    op.drop_index(op.f('ix_news_sentiment'), table_name='news')
    op.drop_index(op.f('ix_news_published_date'), table_name='news')
    op.drop_index(op.f('ix_news_entity_id'), table_name='news')
    op.drop_index('idx_news_source_date', table_name='news')
    op.drop_index('idx_news_sentiment_date', table_name='news')
    op.drop_index('idx_news_entity_date', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_is_active'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_entities_ticker'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
